#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 54.237.40.170:80 check\n\tserver server2 54.197.49.171:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
